/** @type {import('tailwindcss').Config} */
// Tokens Material 3 portados do layout-base (code.html). Cores/spacing/tipografia
// copiados como entregues; única exceção: borderRadius.full mantido em 9999px para
// que pills e avatares circulares fiquem como no mockup (o token original "0.75rem"
// quebraria os círculos).
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#e1e3e4',
        'inverse-surface': '#2e3132',
        'on-surface-variant': '#414844',
        'tertiary-container': '#56340e',
        background: '#f8f9fa',
        'primary-fixed-dim': '#a5d0b9',
        primary: '#012d1d',
        'surface-container-highest': '#e1e3e4',
        'surface-bright': '#f8f9fa',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#002114',
        surface: '#f8f9fa',
        'surface-container-high': '#e7e8e9',
        'on-secondary': '#ffffff',
        outline: '#717973',
        'tertiary-fixed-dim': '#f0bd8b',
        'on-background': '#191c1d',
        'surface-tint': '#3f6653',
        'inverse-primary': '#a5d0b9',
        'primary-fixed': '#c1ecd4',
        'tertiary-fixed': '#ffdcbd',
        'on-error': '#ffffff',
        'on-primary-container': '#86af99',
        'on-primary': '#ffffff',
        secondary: '#506619',
        'on-surface': '#191c1d',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed-variant': '#274e3d',
        'surface-dim': '#d9dadb',
        'surface-container': '#edeeef',
        'on-tertiary-container': '#cd9d6d',
        'secondary-fixed-dim': '#b6d178',
        'secondary-fixed': '#d2ed91',
        'on-secondary-fixed-variant': '#394d00',
        'outline-variant': '#c1c8c2',
        'surface-container-low': '#f3f4f5',
        error: '#ba1a1a',
        'inverse-on-surface': '#f0f1f2',
        tertiary: '#3b1f00',
        'error-container': '#ffdad6',
        'on-secondary-fixed': '#151f00',
        'on-tertiary-fixed': '#2c1600',
        'on-tertiary-fixed-variant': '#623f18',
        'secondary-container': '#cfea8e',
        'primary-container': '#1b4332',
        'on-secondary-container': '#546a1d',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'margin-desktop': '48px',
        unit: '8px',
        'margin-mobile': '16px',
        'container-max-width': '1280px',
      },
      fontFamily: {
        'label-xs': ['JetBrains Mono', 'monospace'],
        'body-md': ['"Source Sans 3"', 'sans-serif'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Work Sans', 'sans-serif'],
        'body-lg': ['"Source Sans 3"', 'sans-serif'],
        'headline-lg-mobile': ['Work Sans', 'sans-serif'],
        'headline-md': ['Work Sans', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'label-xs': ['10px', { lineHeight: '14px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-lg': ['20px', { lineHeight: '30px', fontWeight: '400' }],
        'headline-lg-mobile': ['30px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
